#!/usr/bin/perl
#
# Receives one argument: the name of the program we want to evaluate, 
# which contains the May version of the Televote project.
#
# Assumes the existence of a Makefile with rules to generate a target
# named "televote."
#
# If not, that is, if the program is not generated, it exits with the
# corresponding error message.
#
#
#

use v5.22;
use File::Copy;
use experimental qw(smartmatch);

# use utf8;

# Function show_environment()
# Receives one parameter: the test number
#
sub show_environment {
  if (@_ != 1) {
    say <<'end_of_ca_help_message'; 
Incorrect use of the function show_environment()
usage: show_environment (test_number);
          test_number    number of the test
end_of_ca_help_message
    exit 1;
  }

  my ${test_number} = shift @_;

  say "Boundary conditions:";
  given (${test_number}) {
    when ([0]) {
      say "At the start, the countries file does not exist";
      say "At the start, the votes file does not exist";
      say "The user simply exits";
      say "At the end, an empty countries file should exist";
      say "At the end, an empty votes file should exist";
    }
    when ([1]) {
      say "At the start, an empty countries file exists";
      say "At the start, an empty votes file exists";
      say "The user simply exits";
      say "At the end, an empty countries file should exist";
      say "At the end, an empty votes file should exist";
    }
    when ([2]) {
      say "At the start, the countries file does not exist";
      say "At the start, the votes file does not exist";
      say "The user attempts all operations useless without countries or votes";
      say "At the end, an empty countries file should exist";
      say "At the end, an empty votes file should exist";
    }
    when ([3]) {
      say "At the start, an empty countries file exists";
      say "At the start, an empty votes file exists";
      say "The user inputs incorrect options in the menu and in validate()";
      say "At the end, an empty countries file should exist";
      say "At the end, an empty votes file should exist";
    }
    when ([4]) {
      say "At the start, a file with 6 countries, copy of countriesA.base, exists";
      say "At the start, an empty votes file exists";
      say "The user attempts operations on non-existent countries";
      say "At the end, the same countries file should exist";
      say "At the end, an empty votes file should exist";
    }
    when ([5]) {
      say "At the start, a file with 6 countries, copy of countriesB.base, exists";
      say "At the start, a file with 3 votes, copy of votesB.base, exists";
      say "The user enters incorrect data before providing correct data";
      say "At the end, a countries file with some changes should exist";
      say "At the end, a votes file with some changes should exist";
    }
    when ([6]) {
      say "At the start, an empty countries file exists";
      say "At the start, an empty votes file exists";
      say "The user registers some correct countries";
      say "The user adds some correct votes";
      say "At the end, a countries file identical to countriesC.base should exist";
      say "At the end, a votes file identical to votesC.base should exist";
    }
    when ([7]) {
      say "At the start, a file with some countries, copy of countriesC.base, exists";
      say "At the start, a file with some votes, copy of votesC.base, exists";
      say "The user makes a series of changes";
      say "At the end, a countries file with several changes should exist";
      say "At the end, a votes file with several changes should exist";
    }
    when ([8]) {
      say "At the start, a file with 6 countries, copy of countriesB.base, exists";
      say "At the start, a file with 3 votes, copy of votesB.base, exists";
      say "The user deletes all countries";
      say "At the end, an empty countries file should exist";
      say "At the end, a votes file identical to votesB.base should exist";
    }
    when ([9]) {
      say "At the start, a file with 3 countries, copy of countriesD.base, exists";
      say "At the start, an empty votes file exists";
      say "The user deletes all countries, attempts useless operations, and registers 3 new ones";
      say "At the end, a file with 3 new countries should exist";
      say "At the end, an empty votes file should exist";
    }
  }
  return ;
}

# Function compare_files()
# Receives two parameters: the names of the two files to be compared
#
sub compare_files {
  if (@_ != 2) {
    say <<'end_of_ca_help_message'; 
Incorrect use of the function compare_files()
usage: compare_files (model file);
          model    name of the model to compare the file with
          file     name of the file to be compared with the model
end_of_ca_help_message
    exit 1;
  }

  my ${model} = shift @_;
  my ${file} = shift @_;

  say "\nCompare the file ${file} generated by the program we are";
  say "evaluating to the file ${model} it should have generated,";
  say "and show the differences (if any)\n";

  my ${status} = 0;
  system ("diff -Bw ${model} ${file}");
  if ($? == 0) {
    say "The file [01;32m${file}[00m is correct";
  }
  else {
    say "The file [01;32m${file}[00m is [01;31mNOT[00m correct";
    ${status} = 1;
  }

  say "\nPress enter to continue...";
  my ${continue} = <STDIN>;
  return ${status};
}

# Function move_and_compare()
# Receives two parameters: the names of the two files to be compared
# after ensuring that the one to be evaluated exists
#
sub move_and_compare {
  if (@_ != 2) {
    say <<'end_of_mc_help_message'; 
Incorrect use of the function move_and_compare()
usage: move_and_compare (model file);
         model    name of the model to compare the file with
         file     name of the file to be compared with the model
end_of_mc_help_message
    exit 1;
  }

  my ${model} = shift @_;
  my ${file} = shift @_;
  my ${status} = 0;

  if ( -e "${file}") {
    rename "${file}", "my_${model}";
    ${file}="my_${model}";
    ${status} = compare_files ("${model}", "${file}");
  }
  else {
    say "The file [01;31m${file}[00m does not exist";
    say "Press enter to continue...";
    my ${continue} = <STDIN>;
    ${status} = 1;
  }
  return ${status};
}

# Function check_exists()
# Receives two parameters: the name of the file to check if it exists
# and the model file name that it would have if it existed
#
sub check_exists {
  if (@_ != 2) {
    say <<'end_of_pe_help_message'; 
Incorrect use of the function check_exists()
usage: check_exists (model file);
          model    name of the model file it would be if it existed
          file     name of the file to check for existence
end_of_pe_help_message
    exit 1;
  }

  my ${model} = shift @_;
  my ${file} = shift @_;

  say "\nChecking that the program has not generated a [01;32mmy_${model}[00m\n";

  my ${status} = 0;

  if ( -e "${file}") {
    rename "${file}", "my_${model}";
    ${file}="my_${model}";
    say "The file [01;32m${file}[00m [01;31mshould NOT exist[00m\n";
    say "Press enter to continue...";
    my ${continue} = <STDIN>;
    ${status} = 1;
  }
  return ${status};
}

if (@ARGV != 1) {
say <<'end_of_help_message'; 
   usage: protocol.pl program
          program    name of the program we want to evaluate

end_of_help_message
exit 1;
}

# The protocol itself
#
my ${program} = shift @ARGV;
my ${failed_tests} = 0;
my ${total_tests} = 10;

say "\nProtocol to evaluate a program containing the May version";
say "of the Televote project\n";

say "The program is called: \"${program}\"\n";

if ( ! -e "Makefile") {
  say "No 'Makefile' exists capable of generating the target \"${program}\"\n";
  exit 2;
}

say "Cleaning up the environment";
system ("make clean");
unlink ("countries.txt", "votes.txt", glob("my_countries[0-2][0-9].txt"), glob("my_votes[0-2][0-9].txt"), glob("my_output[0-2][0-9].txt"));

say "\nBuilding the application";
system ("make ${program}");
say "\n";

if ( ! -e "${program}") {
  say "The program ${program} does not exist\n";
  exit 3;
}
elsif ( ! -x "${program}") {
  say "The program ${program} cannot be executed\n";
  exit 4;
}
else {
  say "Running the test suite\n";

  my @a = (0..${total_tests}-1);
  for my ${num} (@a) {
    say "[01;36mTest number ${num}[00m: ./${program} < proto0${num}.txt > my_output0${num}.txt";
    show_environment (${num});
    given (${num}) {
      when ([1, 3]) {
	copy ("countrie0${num}.txt", "countries.txt");
	copy ("votes0${num}.txt", "votes.txt");
      }
      when ([4]) {
	copy ("countriesA.base", "countries.txt");
	copy ("votes04.txt", "votes.txt");
      }
      when ([5]) {
	copy ("countriesB.base", "countries.txt");
	copy ("votesB.base", "votes.txt");
      }
      when ([7]) {
	copy ("countriesC.base", "countries.txt");
	copy ("votesC.base", "votes.txt");
      }
      when ([8]) {
	copy ("countriesB.base", "countries.txt");
	copy ("votesB.base", "votes.txt");
      }
      when ([9]) {
	copy ("countriesD.base", "countries.txt");
	copy ("votes09.txt", "votes.txt");
      }
    }
    system ("ulimit -f 120 ; ./${program} < proto0${num}.txt > my_output0${num}.txt");
    say "\nVerifications:";
    my ${fail_count} = 0;
    ${fail_count} += move_and_compare ("countries0${num}.txt", "countries.txt");
    ${fail_count} += move_and_compare ("votes0${num}.txt", "votes.txt");
    ${fail_count} += compare_files ("output0${num}.txt", "my_output0${num}.txt");
    if (${fail_count} > 0) { ${failed_tests}++; }
  }

  if (${failed_tests} > 0) {
    say "\n[01;31m${failed_tests} failed tests out of ${total_tests}[00m\n"
  }
  else {
    say "\n[01;32mAll tests passed succesfully[00m\n"
  }
  exit ${failed_tests};
}
